// Generated by spider on 2026-05-21 07:14:15.998936

class AppIcons {
  AppIcons._();

  static const String authEmailOtp = 'assets/icons/auth_email_otp.png';
  static const String authForgotPassword =
      'assets/icons/auth_forgot_password.png';
  static const String authLocation = 'assets/icons/auth_location.png';
  static const String authPassword = 'assets/icons/auth_password.png';
  static const String authPhone = 'assets/icons/auth_phone.png';
  static const String authRegister = 'assets/icons/auth_register.png';
  static const String googleLogo = 'assets/icons/google_logo.svg';
}
