// Generated by spider on 2026-05-20 08:11:12.077719

class AppIcons {
  AppIcons._();

  static const String authEmailOtp = 'assets/icons/auth_email_otp.svg';
  static const String authForgotPassword =
      'assets/icons/auth_forgot_password.svg';
  static const String authLocation = 'assets/icons/auth_location.svg';
  static const String authPassword = 'assets/icons/auth_password.svg';
  static const String authPhone = 'assets/icons/auth_phone.svg';
  static const String authRegister = 'assets/icons/auth_register.svg';
  static const String googleLogo = 'assets/icons/google_logo.svg';
}
