// Generated by spider on 2026-05-20 08:11:12.073246

class Images {
  Images._();

  static const String ob2Vendor = 'assets/images/ob2_vendor.png';
  static const String ob3Avatar1 = 'assets/images/ob3_avatar_1.png';
  static const String ob3Avatar2 = 'assets/images/ob3_avatar_2.png';
  static const String ob3Avatar3 = 'assets/images/ob3_avatar_3.png';
  static const String onboarding1 = 'assets/images/onboarding_1.png';
  static const String onboarding2 = 'assets/images/onboarding_2.png';
  static const String onboarding3 = 'assets/images/onboarding_3.png';
  static const String splashLogo = 'assets/images/splash_logo.png';
}
